# Generated by Django 4.0.2 on 2024-01-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(choices=[('', 'Selecione um assunto'), ('desconto', 'Desconto'), ('consultoria', 'Consultoria'), ('freelance', 'Freelance'), ('elogios', 'Elogios'), ('reclamações', 'Reclamações'), ('outros', 'Outros')], default='', max_length=100),
        ),
    ]
