# Generated by Django 4.0.2 on 2023-12-29 08:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0004_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/APPS/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
