# Generated by Django 4.0.2 on 2023-12-29 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0005_post_imagen_capa_post_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 29, 11, 58, 3, 977941, tzinfo=utc)),
        ),
    ]
