# Generated by Django 4.0.2 on 2023-12-29 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0006_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 29, 12, 21, 53, 760263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_capa',
            field=models.ImageField(blank=True, null=True, upload_to='APPS/static/APPS/'),
        ),
    ]
