# Generated by Django 4.0.2 on 2023-12-29 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0007_alter_post_data_publicacao_alter_post_imagen_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 29, 12, 23, 13, 594463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/APPS/'),
        ),
    ]
