# Generated by Django 4.0.2 on 2023-12-29 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0008_alter_post_data_publicacao_alter_post_imagen_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen_capa',
            new_name='imagem_capa',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
